// Generated by gencpp from file actionlib_lutorials/ShapeGoal.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_LUTORIALS_MESSAGE_SHAPEGOAL_H
#define ACTIONLIB_LUTORIALS_MESSAGE_SHAPEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_lutorials
{
template <class ContainerAllocator>
struct ShapeGoal_
{
  typedef ShapeGoal_<ContainerAllocator> Type;

  ShapeGoal_()
    : edges(0)
    , radius(0.0)  {
    }
  ShapeGoal_(const ContainerAllocator& _alloc)
    : edges(0)
    , radius(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _edges_type;
  _edges_type edges;

   typedef float _radius_type;
  _radius_type radius;




  typedef boost::shared_ptr< ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ShapeGoal_

typedef ::actionlib_lutorials::ShapeGoal_<std::allocator<void> > ShapeGoal;

typedef boost::shared_ptr< ::actionlib_lutorials::ShapeGoal > ShapeGoalPtr;
typedef boost::shared_ptr< ::actionlib_lutorials::ShapeGoal const> ShapeGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace actionlib_lutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'actionlib_lutorials': ['/home/ewenwan/ewenwan/catkin_ws/src/actionlib_lutorials/msg', '/home/ewenwan/ewenwan/catkin_ws/devel/share/actionlib_lutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b9202ab7292cebe5a95ab2bf6b9c091";
  }

  static const char* value(const ::actionlib_lutorials::ShapeGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b9202ab7292cebeULL;
  static const uint64_t static_value2 = 0x5a95ab2bf6b9c091ULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_lutorials/ShapeGoal";
  }

  static const char* value(const ::actionlib_lutorials::ShapeGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
int32 edges\n\
float32 radius\n\
";
  }

  static const char* value(const ::actionlib_lutorials::ShapeGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.edges);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShapeGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_lutorials::ShapeGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_lutorials::ShapeGoal_<ContainerAllocator>& v)
  {
    s << indent << "edges: ";
    Printer<int32_t>::stream(s, indent + "  ", v.edges);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_LUTORIALS_MESSAGE_SHAPEGOAL_H
