// Generated by gencpp from file rosserial_mbed/Test.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_MBED_MESSAGE_TEST_H
#define ROSSERIAL_MBED_MESSAGE_TEST_H

#include <ros/service_traits.h>


#include <rosserial_mbed/TestRequest.h>
#include <rosserial_mbed/TestResponse.h>


namespace rosserial_mbed
{

struct Test
{

typedef TestRequest Request;
typedef TestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Test
} // namespace rosserial_mbed


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosserial_mbed::Test > {
  static const char* value()
  {
    return "c63e85f503b805d84df783e71c6bb0d2";
  }

  static const char* value(const ::rosserial_mbed::Test&) { return value(); }
};

template<>
struct DataType< ::rosserial_mbed::Test > {
  static const char* value()
  {
    return "rosserial_mbed/Test";
  }

  static const char* value(const ::rosserial_mbed::Test&) { return value(); }
};


// service_traits::MD5Sum< ::rosserial_mbed::TestRequest> should match 
// service_traits::MD5Sum< ::rosserial_mbed::Test > 
template<>
struct MD5Sum< ::rosserial_mbed::TestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_mbed::Test >::value();
  }
  static const char* value(const ::rosserial_mbed::TestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_mbed::TestRequest> should match 
// service_traits::DataType< ::rosserial_mbed::Test > 
template<>
struct DataType< ::rosserial_mbed::TestRequest>
{
  static const char* value()
  {
    return DataType< ::rosserial_mbed::Test >::value();
  }
  static const char* value(const ::rosserial_mbed::TestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosserial_mbed::TestResponse> should match 
// service_traits::MD5Sum< ::rosserial_mbed::Test > 
template<>
struct MD5Sum< ::rosserial_mbed::TestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_mbed::Test >::value();
  }
  static const char* value(const ::rosserial_mbed::TestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_mbed::TestResponse> should match 
// service_traits::DataType< ::rosserial_mbed::Test > 
template<>
struct DataType< ::rosserial_mbed::TestResponse>
{
  static const char* value()
  {
    return DataType< ::rosserial_mbed::Test >::value();
  }
  static const char* value(const ::rosserial_mbed::TestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSSERIAL_MBED_MESSAGE_TEST_H
