// Generated by gencpp from file industrial_msgs/SetDrivePowerRequest.msg
// DO NOT EDIT!


#ifndef INDUSTRIAL_MSGS_MESSAGE_SETDRIVEPOWERREQUEST_H
#define INDUSTRIAL_MSGS_MESSAGE_SETDRIVEPOWERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace industrial_msgs
{
template <class ContainerAllocator>
struct SetDrivePowerRequest_
{
  typedef SetDrivePowerRequest_<ContainerAllocator> Type;

  SetDrivePowerRequest_()
    : drive_power(false)  {
    }
  SetDrivePowerRequest_(const ContainerAllocator& _alloc)
    : drive_power(false)  {
  (void)_alloc;
    }



   typedef uint8_t _drive_power_type;
  _drive_power_type drive_power;




  typedef boost::shared_ptr< ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetDrivePowerRequest_

typedef ::industrial_msgs::SetDrivePowerRequest_<std::allocator<void> > SetDrivePowerRequest;

typedef boost::shared_ptr< ::industrial_msgs::SetDrivePowerRequest > SetDrivePowerRequestPtr;
typedef boost::shared_ptr< ::industrial_msgs::SetDrivePowerRequest const> SetDrivePowerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace industrial_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'industrial_msgs': ['/home/ewenwan/ewenwan/catkin_ws/src/industrial_core/industrial_msgs/msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad0065fa1febb42851b8c0a0493a1234";
  }

  static const char* value(const ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad0065fa1febb428ULL;
  static const uint64_t static_value2 = 0x51b8c0a0493a1234ULL;
};

template<class ContainerAllocator>
struct DataType< ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "industrial_msgs/SetDrivePowerRequest";
  }

  static const char* value(const ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
bool drive_power\n\
";
  }

  static const char* value(const ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drive_power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDrivePowerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::industrial_msgs::SetDrivePowerRequest_<ContainerAllocator>& v)
  {
    s << indent << "drive_power: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.drive_power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INDUSTRIAL_MSGS_MESSAGE_SETDRIVEPOWERREQUEST_H
