// Generated by gencpp from file industrial_msgs/StartMotion.msg
// DO NOT EDIT!


#ifndef INDUSTRIAL_MSGS_MESSAGE_STARTMOTION_H
#define INDUSTRIAL_MSGS_MESSAGE_STARTMOTION_H

#include <ros/service_traits.h>


#include <industrial_msgs/StartMotionRequest.h>
#include <industrial_msgs/StartMotionResponse.h>


namespace industrial_msgs
{

struct StartMotion
{

typedef StartMotionRequest Request;
typedef StartMotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartMotion
} // namespace industrial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::industrial_msgs::StartMotion > {
  static const char* value()
  {
    return "50b1f38f75f5677e5692f3b3e7e1ea48";
  }

  static const char* value(const ::industrial_msgs::StartMotion&) { return value(); }
};

template<>
struct DataType< ::industrial_msgs::StartMotion > {
  static const char* value()
  {
    return "industrial_msgs/StartMotion";
  }

  static const char* value(const ::industrial_msgs::StartMotion&) { return value(); }
};


// service_traits::MD5Sum< ::industrial_msgs::StartMotionRequest> should match 
// service_traits::MD5Sum< ::industrial_msgs::StartMotion > 
template<>
struct MD5Sum< ::industrial_msgs::StartMotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::industrial_msgs::StartMotion >::value();
  }
  static const char* value(const ::industrial_msgs::StartMotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::industrial_msgs::StartMotionRequest> should match 
// service_traits::DataType< ::industrial_msgs::StartMotion > 
template<>
struct DataType< ::industrial_msgs::StartMotionRequest>
{
  static const char* value()
  {
    return DataType< ::industrial_msgs::StartMotion >::value();
  }
  static const char* value(const ::industrial_msgs::StartMotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::industrial_msgs::StartMotionResponse> should match 
// service_traits::MD5Sum< ::industrial_msgs::StartMotion > 
template<>
struct MD5Sum< ::industrial_msgs::StartMotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::industrial_msgs::StartMotion >::value();
  }
  static const char* value(const ::industrial_msgs::StartMotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::industrial_msgs::StartMotionResponse> should match 
// service_traits::DataType< ::industrial_msgs::StartMotion > 
template<>
struct DataType< ::industrial_msgs::StartMotionResponse>
{
  static const char* value()
  {
    return DataType< ::industrial_msgs::StartMotion >::value();
  }
  static const char* value(const ::industrial_msgs::StartMotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INDUSTRIAL_MSGS_MESSAGE_STARTMOTION_H
