PROJECT         := rosserial_mbed_Odom
DEVICES         := LPC1768 KL25Z NUCLEO_F401RE
GCC4MBED_DIR    := $(GCC4MBED_DIR)
USER_LIBS       := $(ROS_LIB_DIR)
NO_FLOAT_SCANF  := 1
NO_FLOAT_PRINTF := 1

include $(GCC4MBED_DIR)/build/gcc4mbed.mk
