; Auto-generated. Do not edit!


(cl:in-package actionlib_lutorials-msg)


;//! \htmlinclude ShapeGoal.msg.html

(cl:defclass <ShapeGoal> (roslisp-msg-protocol:ros-message)
  ((edges
    :reader edges
    :initarg :edges
    :type cl:integer
    :initform 0)
   (radius
    :reader radius
    :initarg :radius
    :type cl:float
    :initform 0.0))
)

(cl:defclass ShapeGoal (<ShapeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ShapeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ShapeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_lutorials-msg:<ShapeGoal> is deprecated: use actionlib_lutorials-msg:ShapeGoal instead.")))

(cl:ensure-generic-function 'edges-val :lambda-list '(m))
(cl:defmethod edges-val ((m <ShapeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_lutorials-msg:edges-val is deprecated.  Use actionlib_lutorials-msg:edges instead.")
  (edges m))

(cl:ensure-generic-function 'radius-val :lambda-list '(m))
(cl:defmethod radius-val ((m <ShapeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_lutorials-msg:radius-val is deprecated.  Use actionlib_lutorials-msg:radius instead.")
  (radius m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ShapeGoal>) ostream)
  "Serializes a message object of type '<ShapeGoal>"
  (cl:let* ((signed (cl:slot-value msg 'edges)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'radius))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ShapeGoal>) istream)
  "Deserializes a message object of type '<ShapeGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'edges) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'radius) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ShapeGoal>)))
  "Returns string type for a message object of type '<ShapeGoal>"
  "actionlib_lutorials/ShapeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ShapeGoal)))
  "Returns string type for a message object of type 'ShapeGoal"
  "actionlib_lutorials/ShapeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ShapeGoal>)))
  "Returns md5sum for a message object of type '<ShapeGoal>"
  "3b9202ab7292cebe5a95ab2bf6b9c091")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ShapeGoal)))
  "Returns md5sum for a message object of type 'ShapeGoal"
  "3b9202ab7292cebe5a95ab2bf6b9c091")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ShapeGoal>)))
  "Returns full string definition for message of type '<ShapeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 edges~%float32 radius~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ShapeGoal)))
  "Returns full string definition for message of type 'ShapeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 edges~%float32 radius~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ShapeGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ShapeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ShapeGoal
    (cl:cons ':edges (edges msg))
    (cl:cons ':radius (radius msg))
))
