; Auto-generated. Do not edit!


(cl:in-package actionlib_lutorials-msg)


;//! \htmlinclude ShapeFeedback.msg.html

(cl:defclass <ShapeFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ShapeFeedback (<ShapeFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ShapeFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ShapeFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_lutorials-msg:<ShapeFeedback> is deprecated: use actionlib_lutorials-msg:ShapeFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ShapeFeedback>) ostream)
  "Serializes a message object of type '<ShapeFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ShapeFeedback>) istream)
  "Deserializes a message object of type '<ShapeFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ShapeFeedback>)))
  "Returns string type for a message object of type '<ShapeFeedback>"
  "actionlib_lutorials/ShapeFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ShapeFeedback)))
  "Returns string type for a message object of type 'ShapeFeedback"
  "actionlib_lutorials/ShapeFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ShapeFeedback>)))
  "Returns md5sum for a message object of type '<ShapeFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ShapeFeedback)))
  "Returns md5sum for a message object of type 'ShapeFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ShapeFeedback>)))
  "Returns full string definition for message of type '<ShapeFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ShapeFeedback)))
  "Returns full string definition for message of type 'ShapeFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ShapeFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ShapeFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ShapeFeedback
))
