// Generated by gencpp from file ros_arduino_msgs/DigitalWrite.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_DIGITALWRITE_H
#define ROS_ARDUINO_MSGS_MESSAGE_DIGITALWRITE_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/DigitalWriteRequest.h>
#include <ros_arduino_msgs/DigitalWriteResponse.h>


namespace ros_arduino_msgs
{

struct DigitalWrite
{

typedef DigitalWriteRequest Request;
typedef DigitalWriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DigitalWrite
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::DigitalWrite > {
  static const char* value()
  {
    return "9965f904e6efea32066b0a4a77246056";
  }

  static const char* value(const ::ros_arduino_msgs::DigitalWrite&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::DigitalWrite > {
  static const char* value()
  {
    return "ros_arduino_msgs/DigitalWrite";
  }

  static const char* value(const ::ros_arduino_msgs::DigitalWrite&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalWriteRequest> should match 
// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalWrite > 
template<>
struct MD5Sum< ::ros_arduino_msgs::DigitalWriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::DigitalWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalWriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::DigitalWriteRequest> should match 
// service_traits::DataType< ::ros_arduino_msgs::DigitalWrite > 
template<>
struct DataType< ::ros_arduino_msgs::DigitalWriteRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::DigitalWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalWriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalWriteResponse> should match 
// service_traits::MD5Sum< ::ros_arduino_msgs::DigitalWrite > 
template<>
struct MD5Sum< ::ros_arduino_msgs::DigitalWriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::DigitalWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalWriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::DigitalWriteResponse> should match 
// service_traits::DataType< ::ros_arduino_msgs::DigitalWrite > 
template<>
struct DataType< ::ros_arduino_msgs::DigitalWriteResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::DigitalWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::DigitalWriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_DIGITALWRITE_H
