// Generated by gencpp from file ros_arduino_msgs/ServoWrite.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_MSGS_MESSAGE_SERVOWRITE_H
#define ROS_ARDUINO_MSGS_MESSAGE_SERVOWRITE_H

#include <ros/service_traits.h>


#include <ros_arduino_msgs/ServoWriteRequest.h>
#include <ros_arduino_msgs/ServoWriteResponse.h>


namespace ros_arduino_msgs
{

struct ServoWrite
{

typedef ServoWriteRequest Request;
typedef ServoWriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoWrite
} // namespace ros_arduino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_arduino_msgs::ServoWrite > {
  static const char* value()
  {
    return "f90a4a27fdac2d3886d60d19d2b742b2";
  }

  static const char* value(const ::ros_arduino_msgs::ServoWrite&) { return value(); }
};

template<>
struct DataType< ::ros_arduino_msgs::ServoWrite > {
  static const char* value()
  {
    return "ros_arduino_msgs/ServoWrite";
  }

  static const char* value(const ::ros_arduino_msgs::ServoWrite&) { return value(); }
};


// service_traits::MD5Sum< ::ros_arduino_msgs::ServoWriteRequest> should match 
// service_traits::MD5Sum< ::ros_arduino_msgs::ServoWrite > 
template<>
struct MD5Sum< ::ros_arduino_msgs::ServoWriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::ServoWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::ServoWriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::ServoWriteRequest> should match 
// service_traits::DataType< ::ros_arduino_msgs::ServoWrite > 
template<>
struct DataType< ::ros_arduino_msgs::ServoWriteRequest>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::ServoWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::ServoWriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_arduino_msgs::ServoWriteResponse> should match 
// service_traits::MD5Sum< ::ros_arduino_msgs::ServoWrite > 
template<>
struct MD5Sum< ::ros_arduino_msgs::ServoWriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_arduino_msgs::ServoWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::ServoWriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_arduino_msgs::ServoWriteResponse> should match 
// service_traits::DataType< ::ros_arduino_msgs::ServoWrite > 
template<>
struct DataType< ::ros_arduino_msgs::ServoWriteResponse>
{
  static const char* value()
  {
    return DataType< ::ros_arduino_msgs::ServoWrite >::value();
  }
  static const char* value(const ::ros_arduino_msgs::ServoWriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ARDUINO_MSGS_MESSAGE_SERVOWRITE_H
